### ISSUE TITLE
Button background color

### ISSUE THREAD

**Issue by Zia-Sheikh** [umairayub79/MaDialog#2]
Hello, thanks for this awesome efforts, really helpful material. Can I change button's background color? Please guide.
**Your quick response would me much appreciated.**
**Thank You.**

**Comment by umairayub79** [comment]
No such method available right now .

Will add that ASAP

**Comment by Zia-Sheikh** [comment]
Thanks for your support man! I have download your project and customize it. Thanks for your effort
