### ISSUE TITLE
Cant load gifs

### ISSUE THREAD

**Issue by unix14** [umairayub79/MaDialog#3]
`    java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.unix14.android.wouldyourather-gHJhrdsB-RlN9rLHp7ZNeg==/base.apk)
        at umairayub.madialog.MaDialog$Builder.build(MaDialog.java:206)`

**Comment by umairayub79** [comment]
Hey @Unix14 I can't reproduce that error, Gifs are loading just fine for me

**Comment by unix14** [comment]
what version of Glide i should be using?
i think it clashes with my implementation of Glied

**Comment by umairayub79** [comment]
You using glide in your project?

**Comment by umairayub79** [comment]
Well I'm using _glide:4.2.0'_  in the lib and it's loading Gifs just fine
